name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      versions:
        required: false
        type: string

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{fromJson(inputs.versions)}}
    # Map the job outputs to step outputs
    steps:
      - uses: actions/checkout@v2
        with:
          repository: shree1988/reusableworkflow
          ref: main
      - id: step2
        run: ls -ltr
      - id: step3
        run: echo ${{ matrix.node-version }}