name: '🧳 secret test'

on: workflow_call

jobs:
  upload:
    name: "Upload Build Artifact"
    runs-on: ubuntu-latest
    # env:
    #   GITHUB_TOKEN: ${{ github.token }}
    steps:
      - id: sets-a-secret
        run: |
          the_secret="xEr434#$qsdf"
          echo "::add-mask::$the_secret"
          echo "::set-output name=secret-number::$the_secret"
      - run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"