name: 'Caller2'

on:
  push:
  workflow_dispatch:

# jobs:
#   azlogin:
#     uses: shree1988/reusableworkflow/.github/workflows/reusable2.yml@main
#     with:
#         azure-credentials: '${{ secrets.AZURE_CREDENTIALS }}'
#         azure-vault-name: 'testingvault101'

jobs:
  azlogin:
    uses: shree1988/reusableworkflow/.github/workflows/reusable2.yml@main
     with:
       azure-credentials: '${{ secrets.AZURE_CREDENTIALS }}'
       azure-vault-name: 'testingvault101'