name: 'Caller2'

on:
  workflow_dispatch:

# jobs:
#   azlogin:
#     uses: shree1988/reusableworkflow/.github/workflows/reusable2.yml@main
#     with:
#         azure-credentials: '${{ secrets.AZURE_CREDENTIALS }}'
#         azure-vault-name: 'testingvault101'
jobs: 
  reusable:
    uses: shree1988/reusableworkflow/.github/workflows/reusable2.yml@main
    secrets:
      azure-credentials: '${{ secrets.AZURE_CREDENTIALS }}'
      azure-vault-name: 'testingvault101'