name: 'Continuous Integration'

on:
  push:
  workflow_dispatch:

# jobs:
#   azlogin:
#     uses: shree1988/reusableworkflow/.github/workflows/reusable2.yml@main
#     with:
#         azure-credentials: '${{ secrets.AZURE_CREDENTIALS }}'
#         azure-vault-name: 'testingvault101'

jobs:
  azlogin:
    name: credentials
    runs-on: ubuntu-latest

    - name: Set up secret file
      env:
        azure-credentials: '${{ secrets.AZURE_CREDENTIALS }}'
        azure-vault-name: 'testingvault101'