name: 'Reusable workflow for Continuous Integration'
on:
  workflow_call:
    secrets:
      azure-credentials:
       required: true
      azure-vault-name:
       required: true
      USERNAME:
       required: true
      PASSWORD:
       required: true
jobs:
  az-login:
#    using: 'composite'
    runs-on: ubuntu-latest
    steps:
      #- id: az-env
      #  run: |
      #     echo "::set-output name=ArmClientId::$(echo '${{ secrets.azure-credentials }}' | jq -r '.clientId')"
      #     echo "::add-mask::$(echo '${{ secrets.azure-credentials }}' | jq -r '.clientSecret')"
      #     echo "::set-output name=ArmClientSecret::$(echo '${{ secrets.azure-credentials }}' | jq -r '.clientSecret')"
      #     echo "::set-output name=ArmTenantId::$(echo '${{ secrets.azure-credentials }}' | jq -r '.tenantId')"
       # shell: bash
      #- name: az-login
      #  uses: docker://mcr.microsoft.com/azure-cli
      #  with:
      #    entrypoint: az
          #args: login --service-principal -u ${ARM_CLIENT_ID} -p ${ARM_CLIENT_SECRET} -t ${ARM_TENANT_ID}
      #    args: login --service-principal -u ${{ steps.az-env.outputs.ArmClientId }} -p ${{ steps.az-env.outputs.ArmClientSecret }} -t ${{ steps.az-env.outputs.ArmTenantId }}
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.azure-credentials }}

      - id: keyvault
        run: |
          #echo "::set-output name=User::$(az keyvault secret show -n user --vault-name ${{ secrets.azure-vault-name }} -o tsv --query value)"
          #echo "::set-output name=Password::$(az keyvault secret show -n password --vault-name ${{ secrets.azure-vault-name }} -o tsv --query value)"
          echo "::set-output name=User::$(echo '${{ secrets.USERNAME }}')"
          echo "::set-output name=Password::$(echo '${{ secrets.PASSWORD }}')"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: sed
        run: |
          echo "::add-mask::${{ steps.keyvault.outputs.Password }}"
          ls -ltr
          cat 'test.txt'
          sed -i -e 's/##user##/${{ steps.keyvault.outputs.User }}/g' \
          -e 's/##pass##/${{ steps.keyvault.outputs.Password }}/g' \
          'test.txt'
          cat 'test.txt'
      - name: Commit report
        run: |
          git config --global user.name 'test'
          git config --global user.email 'test@users.noreply.github.com'
          git add test.txt
          git commit -am "Automated report"
          git push
      # - name: az-keyvault-secrets
      #   id: keyvault
      #   env:
      #     ARM_CLIENT_ID: ${{ steps.az-env.outputs.ArmClientId }}
      #     ARM_CLIENT_SECRET: ${{ steps.az-env.outputs.ArmClientSecret }}
      #     ARM_TENANT_ID: ${{ steps.az-env.outputs.ArmTenantId }}
      #   uses: docker://mcr.microsoft.com/azure-cli
      #   with:
      #     entrypoint: bash
      #     args: |
      #       -c "echo \"::set-output name=User::$(az keyvault secret show -n user --vault-name ${{ secrets.azure-vault-name }} -o tsv --query value)\";\
      #       echo \"::set-output name=Password::$(az keyvault secret show -n password --vault-name ${{ secrets.azure-vault-name }} -o tsv --query value)\""